from django.conf.urls import patterns, url
from pinyin import views


urlpatterns = \
    patterns('',
             url(r'^$', views.home, name='home'),
             url(r'^add_user_text$', views.add_user_text, name='add_user_text'),
             # url(r'^page/(?P<page_id>\d+)/$', views.page, name='page'),
             # url(r'^question/(?P<question_id>\d+)/$', views.question, name='question'),
             # url(r'^add_answer/$', views.add_answer, name='add_answer'),
             # url(r'^add_question/$', views.add_question, name='add_question'),
             # url(r'^edit_question/$', views.edit_question, name='edit_question'),
             # url(r'^edit_page/$', views.edit_page, name='edit_page'),
             # url(r'^add_page/$', views.add_page, name='add_page'),
             # url(r'^add_comment/$', views.add_comment, name='add_comment'),
             # url(r'^add_vote/$', views.add_vote, name='add_vote'),
             # url(r'^tag/(?P<tag_id>\d+)/$', views.tag, name='tag'),
             # url(r'^tag/$', views.tag_base, name='tag_base'),v
             # url(r'^list_of_tags_ajax$', views.list_of_tags_ajax, name='list_of_tags_ajax'),
             # url(r'^edit_tags/$', views.edit_tags, name='edit_tags'),
             # url(r'^search/$', views.search, name='search'),
             # url(r'^suggested_results/$', views.suggested_results, name='suggested_results'),
             # url(r'^login/$', views.login, name='login'),
             # url(r'^logout/$', views.logout, name='logout'),
             # url(r'^signup/(?P<invitationHash>[0-9A-Za-z_]+)$', views.signup, name='signup'),
             # url(r'^share/$', views.share, name='share'),
             # url(r'^incorrectInvite/$', views.incorrectInvite, name='incorrectInvite'),
             # url(r'^admin/users/$', views.admin_users, name='admin_users'),
             # url(r'^admin/account/$', views.admin_account, name='admin_account'),
             # url(r'^admin/account/edit_account_plan$', views.edit_account_plan, name='edit_account_plan'),
             # url(r'^admin/roles_permissions/$', views.admin_roles_permissions, name='admin_roles_permissions'),
             # url(r'^admin/roles_permissions/edit_role$', views.admin_edit_role, name='admin_edit_role'),
             # url(r'^list_of_people_ajax$', views.list_of_people_ajax, name='list_of_people_ajax'),
             # url(r'^list_of_permissions_ajax', views.list_of_permissions_ajax, name='list_of_permissions_ajax'),
             # url(r'^remove_user_ajax/$', views.remove_user_ajax, name='remove_user_ajax'),
             # url(r'^password_reset_ajax/$', views.password_reset_ajax, name='password_reset_ajax'),
             # url(r'^password_reset/$', views.password_reset, name='password_reset'),
             # url(r'^password_reset_done/$', views.password_reset_done, name='password_reset_done'),
             # url(r'^password_reset_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', views.password_reset_confirm,
             #     name='password_reset_confirm'),
             # url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='profile'),
             # url(r'^feedback/$', views.add, name='feedback'),
             # url(r'^subscribe/$', views.subscribe, name='subscribe'),
    )
